### ISSUE TITLE
possible bug in utils.py

### ISSUE THREAD

**Issue by materialvision** [galgreshler/Catch-A-Waveform#4]
I get an error with this line when trying to segment a file with the param segments_to_train
line 192:   _samples, _ = librosa.load(params.input_path, sr=None,

since params.input_path does not exist...

when I exchange for 
_samples, _ = librosa.load(os.path.join('inputs', params.input_file), sr=None,

it seems to work as expected

Thanks for a great model!

**Comment by galgreshler** [comment]
You're right, I pushed a fix. Thanks
