### ISSUE TITLE
Running the code directly does not get the reported results

### ISSUE THREAD

**Issue by wjy66** [galgreshler/Catch-A-Waveform#6]
Hi, thank you for your work. 
But I can't get the reported results when I ues "python train_main.py --input_file FMA_rock_for_inpainting"
May I ask if there are any parameters that need to be modified?

**Comment by galgreshler** [comment]
Hi, yes you have to provide extra parameters:

python train_main.py --input_file FMA_rock_for_inpainting --run_mode inpainting --inpainting_indices 89164 101164
